cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - node -v
        - npm install -g danger
        - make install
      script:
        - swift test
        # - DEBUG="*" danger process .build/x86_64-apple-macosx10.10/debug/danger-swift
        # - DEBUG="*" danger ci --process .build/x86_64-apple-macosx10.10/debug/danger-swift
        # - sudo chmod -R a+rwx /usr/local/Cellar/
        # - DEBUG="*" danger-swift ci
        # - DEBUG="*" .build/x86_64-apple-macosx10.10/debug/danger-swift ci
        - .build/x86_64-apple-macosx10.10/debug/danger-swift ci

    - os: osx
      osx_image: xcode10
      install:
        - echo "Installing and testing via homebrew"
        - brew tap danger/tap
        - brew install danger-swift
      script:
        - danger-swift pr https://github.com/danger/swift/pull/153

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
      script:
        - swift test
        - sudo chmod -R a+rwx /usr/local/
        - make install
        - DEBUG="*" danger-swift ci
        - cat /tmp/danger-response.json

    - os: osx
      name: Danger with SPM
      osx_image: xcode10
      install:
        - node -v
        - npm install -g danger
      script:
        - swift run danger-swift ci

    - os: linux
      name: Danger with SPM
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
      script:
        - swift run danger-swift ci
        - cat /tmp/danger-response.json
