os: linux
language: generic
sudo: required
dist: trusty

install:
  - node -v
  - npm install -g danger@alpha
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swift build 

script:
  - swift test
  - danger process .build/x86_64-unknown-linux/debug/danger-swift
