cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      install:
        - node -v
        - npm install -g danger
        - make install
      script:
        - swift test
        - danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: bionic
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1.1
      script:
        - swift test
        - sudo chmod -R a+rwx /usr/local/
        - make install
        - DEBUG="*" danger-swift ci

    - os: osx
      osx_image: xcode11.5
      name: Danger Dependencies
      install:
        - node -v
        - npm install -g danger
        - make install
      script:
        - mkdir Test
        - mv DangerfileWithDependencies.swift Test
        - cd Test && danger-swift ci --dangerfile DangerfileWithDependencies.swift --id Dependencies_Test


    - os: osx
      name: Danger with SPM
      osx_image: xcode11.2
      install:
        - node -v
        - npm install -g danger
      script:
        - swift run danger-swift ci

    - os: osx
      name: Xcode 11.4
      osx_image: xcode11.4
      install:
        - node -v
        - npm install -g danger
      script:
        - swift run danger-swift ci

    - os: linux
      name: Danger with SPM
      language: generic
      sudo: required
      dist: bionic
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1.1
      script:
        - swift run danger-swift ci

    - os: linux
      name: Danger with SPM
      language: generic
      sudo: required
      dist: bionic
      install:
        - node -v
        - npm install -g danger
        - echo 5.2.2 > .swift-version
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.2.2
      script:
        - swift run danger-swift ci
