# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2

      - name: Export tag version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        
      - name: Create release
        run: ./Scripts/release_changelog.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
