name: Release Danger-Swift package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Export tag version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Docker Login
      run: echo $PACKAGES_WRITE_TOKEN | docker login docker.pkg.github.com -u $USERNAME --password-stdin
      env:
        PACKAGES_WRITE_TOKEN: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}

    - name: Docker Build
      run: docker build -t docker.pkg.github.com/danger/danger-swift/danger-swift:$VERSION .
      env:
        USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}

    - name: Deploy
      run: docker push docker.pkg.github.com/danger/danger-swift/danger-swift:$VERSION
      env:
        USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}
